name: mindmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  implicitly_animated_reorderable_list_2: ^0.6.0
  flutter_local_notifications: ^19.4.2
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1
  supabase_flutter: ^2.5.8
  shared_preferences: ^2.2.3
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.5
  dart_openai: ^6.1.1
  app_links: ^6.1.4
  fl_chart: ^1.1.0
  logger: ^2.0.2+1
  http: ^1.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  uuid: ^4.5.1
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon2.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
